import {LoginButton} from "@/components/login-logout";
import Providers from "@/components/providers";
import UserButton from "@/components/user-button";
import { getServerAuthSession } from "@/server/auth";
import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await getServerAuthSession();
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <Providers>
        <Toaster position="top-center" reverseOrder={false} />
        <body>
          <div className="flex flex-row items-center justify-center bg-accent py-4 mb-4">
            {session ? <UserButton session={session} /> : <LoginButton />}
          </div>
          <div className="mx-2">{children}</div>
        </body>
      </Providers>
    </html>
  );
}
